x-app: &app
  restart: no #always
  env_file:
    - .env
  volumes:
    - .:/code
  links:
    - db
    - redis

services:
  migrate:
    <<: *app
    depends_on:
      - db
      - redis
    build: 
      context: .
      dockerfile: Dockerfile.app
    command: ["./entrypoint_migrate.sh"]
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
  web:
    <<: *app
    depends_on:
      - db
      - redis
      - migrate
    build: 
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "127.0.0.1:8000:443"
  celery:
    <<: *app
    depends_on:
      - db
      - redis
      - migrate
    build: 
      context: .
      dockerfile: Dockerfile.celery
  beat:
    <<: *app
    depends_on:
      - db
      - redis
      - migrate
    build: 
      context: .
      dockerfile: Dockerfile.beat