version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging / auth in to Amazon ECR
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 528757822565.dkr.ecr.us-west-1.amazonaws.com

  build:
    commands:
      - echo Build started
      - echo Building the django-app docker image
      - docker build -t 528757822565.dkr.ecr.us-west-1.amazonaws.com/ab-django-app-ecr:latest -f build_files/Dockerfile.app .

  post_build:
    commands:
      - echo build completed
      - echo pushing django app image in to docker ECR...
      - docker push 528757822565.dkr.ecr.us-west-1.amazonaws.com/ab-django-app-ecr:latest
      - echo Writing django app image definition file..
      - aws ecs describe-task-definition --task-definition ab-app-task > ab-app-task.json
      - aws ecs describe-task-definition --task-definition ab-migrate-task > ab-migrate-task.json
      - cat ab-migrate-task.json
      - cat ab-app-task.json
     
artifacts:
  files:
    - ab-app-task.json
    - ab-migrate-task.json