version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging / auth in to Amazon ECR
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 528757822565.dkr.ecr.us-west-1.amazonaws.com

  build:
    commands:
      - echo Build started
      - echo Building the django-app docker image
      - docker build -t 528757822565.dkr.ecr.us-west-1.amazonaws.com/ab-django-app-ecr:latest -f build_files/Dockerfile.app .

  post_build:
    commands:
      - echo build completed
      - echo pushing django app image in to docker ECR...
      - docker push 528757822565.dkr.ecr.us-west-1.amazonaws.com/ab-django-app-ecr:latest
      - echo Writing django app image definition file..
      - printf '[{"name":"%s","imageUri":"%s"}]' "ab-django-app" "528757822565.dkr.ecr.us-west-1.amazonaws.com/ab-django-app-ecr:latest" > imagedefinitions_app.json
      - printf '[{"name":"%s","imageUri":"%s"}]' "ab-migrate" "528757822565.dkr.ecr.us-west-1.amazonaws.com/ab-django-app-ecr:latest" > imagedefinitions_app.json
     
artifacts:
  files:
    - imagedefinitions_app.json